//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TntBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TntBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid base name..
        /// </summary>
        public static string BaseNameValidationRuleMessage {
            get {
                return ResourceManager.GetString("BaseNameValidationRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output folder.
        /// </summary>
        public static string Download_OutputFolder {
            get {
                return ResourceManager.GetString("Download_OutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading finished!.
        /// </summary>
        public static string DownloadingFinishedMessage {
            get {
                return ResourceManager.GetString("DownloadingFinishedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading album {0} - photo {1}....
        /// </summary>
        public static string DownloadingPhotoMessage {
            get {
                return ResourceManager.GetString("DownloadingPhotoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Photos.
        /// </summary>
        public static string DownloadPhotosButton {
            get {
                return ResourceManager.GetString("DownloadPhotosButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error downloading the albums : {0}.
        /// </summary>
        public static string ErrorDownloadingAlbumsLog {
            get {
                return ResourceManager.GetString("ErrorDownloadingAlbumsLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in album {0}, photo {1} : {2}.
        /// </summary>
        public static string ErrorDownloadingPhotoLog {
            get {
                return ResourceManager.GetString("ErrorDownloadingPhotoLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the base-name of the social network..
        /// </summary>
        public static string InputBaseNameMessage {
            get {
                return ResourceManager.GetString("InputBaseNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string InstructionsHeader {
            get {
                return ResourceManager.GetString("InstructionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in into your account with your user and password..
        /// </summary>
        public static string InstructionsLine1 {
            get {
                return ResourceManager.GetString("InstructionsLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After entering, please press download photos..
        /// </summary>
        public static string InstructionsLine2 {
            get {
                return ResourceManager.GetString("InstructionsLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading album &quot;{0}&quot;, page {1}....
        /// </summary>
        public static string NextPageDetectedMessage {
            get {
                return ResourceManager.GetString("NextPageDetectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving photo &quot;{0}&quot; in &quot;{1}&quot;....
        /// </summary>
        public static string SavingPhotoMessage {
            get {
                return ResourceManager.GetString("SavingPhotoMessage", resourceCulture);
            }
        }
    }
}
