//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TntBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TntBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string AcceptButton {
            get {
                return ResourceManager.GetString("AcceptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pablo Caballero.
        /// </summary>
        public static string AuthorButtonContent {
            get {
                return ResourceManager.GetString("AuthorButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to author profile.
        /// </summary>
        public static string AuthorButtonToolTip {
            get {
                return ResourceManager.GetString("AuthorButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid base name..
        /// </summary>
        public static string BaseNameValidationRuleMessage {
            get {
                return ResourceManager.GetString("BaseNameValidationRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySocialNetwork.
        /// </summary>
        public static string BaseNameWatermark {
            get {
                return ResourceManager.GetString("BaseNameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output folder.
        /// </summary>
        public static string Download_OutputFolder {
            get {
                return ResourceManager.GetString("Download_OutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading finished!.
        /// </summary>
        public static string DownloadingFinishedMessage {
            get {
                return ResourceManager.GetString("DownloadingFinishedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading album {0} - photo {1}....
        /// </summary>
        public static string DownloadingPhotoMessage {
            get {
                return ResourceManager.GetString("DownloadingPhotoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Photos.
        /// </summary>
        public static string DownloadPhotosButton {
            get {
                return ResourceManager.GetString("DownloadPhotosButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error downloading the albums : {0}.
        /// </summary>
        public static string ErrorDownloadingAlbumsLog {
            get {
                return ResourceManager.GetString("ErrorDownloadingAlbumsLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in album {0}, photo {1} : {2}.
        /// </summary>
        public static string ErrorDownloadingPhotoLog {
            get {
                return ResourceManager.GetString("ErrorDownloadingPhotoLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the base name of the social network..
        /// </summary>
        public static string InputBaseNameMessage {
            get {
                return ResourceManager.GetString("InputBaseNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string InstructionsHeader {
            get {
                return ResourceManager.GetString("InstructionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in into your account with your user and password..
        /// </summary>
        public static string InstructionsLine1 {
            get {
                return ResourceManager.GetString("InstructionsLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After entering, please press download photos..
        /// </summary>
        public static string InstructionsLine2 {
            get {
                return ResourceManager.GetString("InstructionsLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                     GNU GENERAL PUBLIC LICENSE
        ///                       Version 2, June 1991
        ///
        /// Copyright (C) 1989, 1991 Free Software Foundation, Inc., &lt;http://fsf.org/&gt;
        /// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///                            Preamble
        ///
        ///  The licenses for most software are designed to take away your
        ///freedom to share and change it.  By contrast, the [rest of string was truncated]&quot;;.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string LicenseButtonContent {
            get {
                return ResourceManager.GetString("LicenseButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the license.
        /// </summary>
        public static string LicenseButtonToolTip {
            get {
                return ResourceManager.GetString("LicenseButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GNU GENERAL PUBLIC LICENSE.
        /// </summary>
        public static string LicenseContent {
            get {
                return ResourceManager.GetString("LicenseContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TNT Bot License.
        /// </summary>
        public static string LicenseMainInstruction {
            get {
                return ResourceManager.GetString("LicenseMainInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string LicenseWindowTitle {
            get {
                return ResourceManager.GetString("LicenseWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TNT Bot - http://deidigitalis.github.io/TntBot/.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading album &quot;{0}&quot;, page {1}....
        /// </summary>
        public static string NextPageDetectedMessage {
            get {
                return ResourceManager.GetString("NextPageDetectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify Issue.
        /// </summary>
        public static string NotifyIssueButtonContent {
            get {
                return ResourceManager.GetString("NotifyIssueButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the TNT Bot web in github for notifing an issue.
        /// </summary>
        public static string NotifyIssueButtonToolTip {
            get {
                return ResourceManager.GetString("NotifyIssueButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving photo &quot;{0}&quot; in &quot;{1}&quot;....
        /// </summary>
        public static string SavingPhotoMessage {
            get {
                return ResourceManager.GetString("SavingPhotoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string ShowInformationAboutSourceButtonContent {
            get {
                return ResourceManager.GetString("ShowInformationAboutSourceButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://deidigitalis.github.io/TntBot/.
        /// </summary>
        public static string ShowInformationAboutSourceButtonToolTip {
            get {
                return ResourceManager.GetString("ShowInformationAboutSourceButtonToolTip", resourceCulture);
            }
        }
    }
}
